---
- name: "apt : Write configuration files"
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
    mode: 0644
  loop:
    - /etc/apt/sources.list
    - /etc/apt/apt.conf.d/02proxy

- name: "apt : Update cache and packages"
  apt:
    autoremove: yes
    purge: yes
    update_cache: yes
    upgrade: full

- name: "apt : Install additional packages"
  apt:
    name: "{{ debian_packages }}"
    state: latest
