---
- name: Checking variables types and values
  fail:
    msg: Invalid a variables type or value, please check
  when: >-
    gearman_config is not mapping            or
    gearman_use_tmpfs_for is string          or
    gearman_use_tmpfs_for is not sequence

- name: Install 'python-apt' as dependency for checking mode
  apt:
    name: python-apt
    state: latest
  check_mode: no

- name: Pin the actual version
  copy:
    content: |
      Package: gearman-*
      Pin: version {{ _gearman_version }}-*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/00gearman
    mode: 0644

- name: Install packages
  apt:
    name:
      - gearman-job-server
      - gearman-tools
    state: latest

- name: Mount 'tmpfs' on directories
  mount:
    fstype: tmpfs
    opts: mode=0755,uid=gearman,gid=gearman
    path: "{{ item }}"
    src: tmpfs
    state: mounted
  loop: "{{ gearman_use_tmpfs_for }}"
  notify:
    - Restart 'gearman-job-server' service

- name: Write configuration files
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
  loop:
    - /etc/default/gearman-job-server
  notify:
    - Restart 'gearman-job-server' service

- meta: flush_handlers
