---
- name: Checking variables types and values
  fail:
    msg: Invalid a variables type or value, please check
  when: >-
    kernel_params_sysctl is not mapping    or
    kernel_params_sysfs is not mapping

- name: Install 'python-apt' as dependency for checking mode
  apt:
    name: python-apt
    state: latest
  check_mode: no

- name: Install packages
  apt:
    name:
      - sysfsutils
    state: latest
  when:
    - kernel_params_sysfs | length > 0

- name: Write 'sysctl' configuration files
  template:
    src: etc/sysctl.d/sysctl.conf.j2
    dest: &sysctl_dest "/etc/sysctl.d/{{ item.key }}.conf"
  loop: "{{ kernel_params_sysctl | dict2items }}"
  loop_control:
    label: *sysctl_dest
  notify:
    - Reload 'sysctl' settings
  tags:
    - kernel_params_config

- name: Write 'sysfs' configuration files
  template:
    src: etc/sysfs.d/sysfs.conf.j2
    dest: &sysfs_dest "/etc/sysfs.d/{{ item.key }}.conf"
  loop: "{{ kernel_params_sysfs | dict2items }}"
  loop_control:
    label: *sysfs_dest
  notify:
    - Reload 'sysfs' settings
  tags:
    - kernel_params_config

- meta: flush_handlers
