---
- name: "systemd : Create directory for service settings"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/systemd/system/rabbitmq-server.service.d

- name: "systemd : Write the configuration"
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
  loop:
    - /etc/systemd/system/rabbitmq-server.service.d/limitnofile.conf
  notify:
    - Restart 'rabbitmq-server' service
