---
- name: Checking variables types and values
  fail:
    msg: Invalid a variables type or value, please check
  when: >-
    openvpn_configs is not mapping

- name: Install 'python-apt' as dependency for checking mode
  apt:
    name: python-apt
    state: latest
  check_mode: no

- name: Pin the actual version
  copy:
    content: |
      Package: openvpn
      Pin: version {{ _openvpn_version }}-*
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/00openvpn
    mode: 0644

- name: Install packages
  apt:
    name:
      - openvpn
    state: latest

- name: Create a directory
  file:
    dest: "{{ item }}"
    state: directory
  loop:
    - /etc/systemd/system/openvpn@.service.d

- name: Set a 'restart=always' for all OpenVPN tunnels
  copy:
    content: |
      [Service]
      Restart=always
    dest: /etc/systemd/system/openvpn@.service.d/restart_always.conf
  notify:
    - Reload 'systemd' daemon (openvpn)

- block:
  - name: Write tunnels configurations
    template:
      src: etc/openvpn/openvpn.conf.j2
      dest: "/etc/openvpn/{{ item.key }}.conf"
    when:
      - item.value != None
    loop: "{{ openvpn_configs | dict2items }}"
    loop_control:
      label: "{{ item.key }}"
    register: __openvpn_write_tunnel_configurations

  - name: Restart tunnels
    service:
      enabled: yes
      name: "openvpn@{{ item.key }}"
      state: restarted
    when:
      - __openvpn_write_tunnel_configurations.results | selectattr('item', 'defined') | selectattr('item.key', 'equalto', item.key) | list | count > 0
      - __openvpn_write_tunnel_configurations.results | selectattr('item', 'defined') | selectattr('item.key', 'equalto', item.key) | map(attribute='changed') | first == True
    loop: "{{ openvpn_configs | dict2items }}"
  tags:
    - openvpn_configs

- meta: flush_handlers
