---
- name: Checking variables types and values
  fail:
    msg: Invalid a variables type or value, please check
  when: >-
    elasticsearch5_config is not mapping                or
    elasticsearch5_jvm_options is not mapping           or
    elasticsearch5_logs_keep_days is not string         or
    elasticsearch5_plugins is string                    or
    elasticsearch5_plugins is not sequence

- name: Install 'python-apt' as dependency for checking mode
  apt:
    name: python-apt
    state: latest
  check_mode: no

- name: Fetch a package
  get_url:
    checksum: "{{ _elasticsearch5_deb_checksum }}"
    url: "{{ _elasticsearch5_deb_url }}"
    dest: "{{ _elasticsearch5_deb_path }}"

- name: Install packages
  apt:
    deb: "{{ item.startswith('/') | ternary(item, omit) }}"
    dpkg_options: force-confdef,force-confold,skip-same-version
    name: "{{ item.startswith('/') | ternary(omit, item) }}"
    state: "{{ item.startswith('/') | ternary('present', 'latest') }}"
  loop:
    - openjdk-8-jre-headless
    - "{{ _elasticsearch5_deb_path }}"
  loop_control:
    label: "{{ item | basename }}"

- name: Install plugins
  shell:
    chdir: /usr/share/elasticsearch
    cmd: |
      if ! bin/elasticsearch-plugin list | fgrep --silent {{ item }}
      then
        echo "y" | bin/elasticsearch-plugin install {{ item }}
      fi
  loop: "{{ elasticsearch5_plugins }}"
  register: __elasticsearch5_install_plugins
  changed_when: "'-> Installed %s' % (item) in __elasticsearch5_install_plugins.stdout"

- name: Install a cron job for purging old log files
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
    mode: 0755
  loop:
    - /etc/cron.daily/remove_old_elasticsearch_logs
  tags:
    - elasticsearch5_cron

- name: Write configuration files
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
    mode: 0644
  loop:
    - /etc/elasticsearch/elasticsearch.yml
    - /etc/elasticsearch/jvm.options
    - /etc/elasticsearch/log4j2.properties
  notify:
    - Restart 'elasticsearch' service
  tags:
    - elasticsearch5_config

- name: Modify the systemd service configuration
  include_tasks: elasticsearch5_systemd.yml
  when:
    - elasticsearch5_config["bootstrap.memory_lock"] is defined
    - elasticsearch5_config["bootstrap.memory_lock"] == True
  tags:
    - elasticsearch5_systemd

- meta: flush_handlers
