---
- name: Stop 'racoon' service
  service:
    name: racoon
    state: stopped

# This operation is separated for correct shutdown the 'racoon' service
- name: Disable 'racoon' service
  service:
    enabled: no
    name: racoon

- name: Restart 'racoon-tool' service
  systemd:
    daemon_reload: yes
    enabled: yes
    name: racoon-tool
    state: restarted
