---
- name: Reload 'systemd' daemon (elasticsearch1)
  systemd:
    daemon_reload: yes

- name: Restart 'elasticsearch' service
  service:
    enabled: yes
    name: elasticsearch
    state: restarted
