---
- name: Checking variables types and values
  fail:
    msg: Invalid a variables type or value, please check
  when: >-
    php56_fpm_components is string                  or
    php56_fpm_components is not sequence            or
    php56_fpm_config is not mapping                 or
    php56_fpm_pools is not mapping                  or
    php56_fpm_pools_defaults is not mapping         or
    php56_fpm_ini is not mapping

- name: Install 'python-apt' as dependency for checking mode
  apt:
    name: python-apt
    state: latest
  check_mode: no

- name: Add a repository key
  apt_key:
    url: "{{ _php56_fpm_repository_key_url }}"

- name: Add a repository
  apt_repository:
    repo: "deb {{ _php56_fpm_repository_url }} {{ ansible_facts.distribution_release }} main"
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ ['php5.6'] | product(php56_fpm_components + ['cli', 'fpm']) | map('join', '-') | list }}"
    state: latest
  notify:
    - Remove 'www' pool (php56_fpm)

- import_tasks: php56_fpm_systemd.yml
  tags:
    - php56_fpm_systemd

- name: Create directories for logs
  file:
    path: "{{ item }}"
    mode: 0700
    state: directory
  loop: "{{ php56_fpm_pools | json_query('*.[\"access.log\", slowlog]') | flatten | map('dirname') | list | unique }}"

- name: Write configuration files
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
    mode: 0644
  loop:
    - /etc/php/5.6/fpm/php.ini
    - /etc/php/5.6/fpm/php-fpm.conf
  notify:
    - Restart 'php5.6-fpm' service
  tags:
    - php56_fpm_config

- name: Write pools configuration files
  template:
    src: etc/php/5.6/fpm/pool.d/pool.conf.j2
    dest: &pool_conf_path "/etc/php/5.6/fpm/pool.d/{{ item.key }}.conf"
    mode: 0644
  loop: "{{ php56_fpm_pools | dict2items }}"
  loop_control:
    label: *pool_conf_path
  when:
    - item.value != None
    - item.value != {}
  notify:
    - Reload 'php5.6-fpm' service
  tags:
    - php56_fpm_pools

- meta: flush_handlers
