---
- name: Reload 'systemd' daemon (nginx)
  systemd:
    daemon_reload: yes

- name: Reload 'nginx' service
  service:
    name: nginx
    state: reloaded

- name: Restart 'nginx' service
  service:
    name: nginx
    state: restarted

- name: Delete 'default' site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - Restart 'nginx' service
  when:
    - "'default' not in nginx_sites_configs"
