---
- name: Remove 'www' pool
  file:
    path: /etc/php/5.6/fpm/pool.d/www.conf
    state: absent
  when:
    - php56_fpm_pools["www"] == None

- name: Reload 'systemd' daemon
  systemd:
    daemon_reload: yes

- name: Reload 'php5.6-fpm' service
  service:
    name: php5.6-fpm
    state: reloaded

- name: Restart 'php5.6-fpm' service
  service:
    name: php5.6-fpm
    state: restarted
