---
- name: Remove 'www' pool (php56_fpm)
  file:
    path: /etc/php/5.6/fpm/pool.d/www.conf
    state: absent
  when:
    - php56_fpm_pools["www"] is defined
    - php56_fpm_pools["www"] == None or php56_fpm_pools["www"] | count < 1

- name: Reload 'systemd' daemon (php56_fpm)
  systemd:
    daemon_reload: yes

- name: Reload 'php5.6-fpm' service
  service:
    name: php5.6-fpm
    state: reloaded

- name: Restart 'php5.6-fpm' service
  service:
    name: php5.6-fpm
    state: restarted
