---
- name: Remove 'www' pool (php72_fpm)
  file:
    path: /etc/php/7.2/fpm/pool.d/www.conf
    state: absent
  when:
    - php72_fpm_pools["www"] == None

- name: Reload 'systemd' daemon (php72_fpm)
  systemd:
    daemon_reload: yes

- name: Reload 'php7.2-fpm' service
  service:
    name: php7.2-fpm
    state: reloaded

- name: Restart 'php7.2-fpm' service
  service:
    name: php7.2-fpm
    state: restarted
