---
- name: Checking variables types and values
  fail:
    msg: Invalid a variables type or value, please check
  when: >-
    netdata_configs is not mapping

- name: Install 'python-apt' as dependency for checking mode
  apt:
    name: python-apt
    state: latest
  check_mode: no

- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ _netdata_dir }}"

- name: Copy and unpack binary archive
  unarchive:
    creates: "{{ _netdata_dir }}/etc/netdata/stream.conf"
    extra_opts:
      - --strip-components=1
    src: "{{ _netdata_binary_name }}"
    dest: "{{ _netdata_dir }}"

- name: Install dependencies
  apt:
    name:
      - util-linux
      - zlib1g
      - curl
    state: latest

- name: Add system group
  group:
    name: netdata
    system: yes
  tags:
    - netdata_user

- name: Add system user
  user:
    createhome: no
    group: netdata
    home: /
    name: netdata
    shell: /usr/sbin/nologin
    system: yes
  tags:
    - netdata_user

- name: Set owner to files
  file:
    path: "{{ _netdata_dir }}/{{ item.strip('/') }}"
    group: netdata
    owner: netdata
    recurse: yes
  loop:
    - /etc/netdata
    - /usr/share/netdata/web
    - /var/cache/netdata
    - /var/lib/netdata
    - /var/log/netdata
  tags:
    - netdata_user

- name: Install systemd'es service file
  template:
    src: "{{ item.strip('/') }}.j2"
    dest: "{{ item }}"
  loop:
    - /etc/systemd/system/netdata.service
  notify:
    - Enable 'netdata' service

- name: Install configuration for 'logrotate'
  file:
    src: "{{ _netdata_dir }}/etc/logrotate.d/netdata"
    dest: "/etc/logrotate.d/netdata-{{ _netdata_version }}"
    state: link

- name: Write configuration files
  template:
    src: "etc/netdata/{{ item.key }}.conf.j2"
    dest: "{{ _netdata_dir }}/etc/netdata/{{ item.key }}.conf"
    owner: netdata
    group: netdata
    mode: 0644
  with_dict: "{{ netdata_configs }}"
  notify:
    - Restart 'netdata' service
  tags:
    - netdata_config
