---
- name: "current_symlink : Link current folder to new release via symlink"
  throttle: 1
  # Using 'shell' instead on 'file' module for properly working of pause
  shell:
    cmd: >-
      ln --symbolic
        --force
        --no-target-directory
        "{{ _app_deploy_version_dir }}"
        "{{ _app_deploy_current_dir }}"
      ;
      {% if play_hosts | count > 1 %}
      sleep 5
      {% endif %}
    warn: no
