---
- name: Remove 'www' pool (php71_fpm)
  file:
    path: /etc/php/7.1/fpm/pool.d/www.conf
    state: absent
  when:
    - php71_fpm_pools["www"] == None

- name: Reload 'systemd' daemon (php71_fpm)
  systemd:
    daemon_reload: yes

- name: Reload 'php7.1-fpm' service
  service:
    name: php7.1-fpm
    state: reloaded

- name: Restart 'php7.1-fpm' service
  service:
    name: php7.1-fpm
    state: restarted
